name: Build and Release EDK2 for AArch64 GZVM

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: AnyLaySys/edk2-aarch64-gzvm
          path: edk2-aarch64-gzvm

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt -y upgrade
          sudo apt -y install python3-venv pip git mono-devel build-essential nuget build-essential uuid-dev iasl nasm gcc-aarch64-linux-gnu python3 python3-distutils python3-git python3-pip gettext locales gnupg ca-certificates python3-venv git git-core clang llvm curl jq clang llvm gcc-aarch64-linux-gnu
      - name: Build firmware
        working-directory: edk2-aarch64-gzvm
        run: |
          chmod +x ./make.sh
          export TERM=linux
          ./make.sh

      - name: Package build artifacts
        working-directory: edk2-aarch64-gzvm
        run: tar -czvf ../build.tar.gz build/

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
